services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./services/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5

  ingestion:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    working_dir: /app/services
    container_name: ingestion_service
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PYTHONPATH: /app
    command: uvicorn services.ingestion.ingestion_service:app --host 0.0.0.0 --port 8001 --reload

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: api_service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PYTHONPATH: /app
    command: uvicorn api.search_service:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pg_data:
